FORMAT: 1A
HOST: http://www.google.com

# RmtCtrl
RmtCtrl API provides remote control functionality to a server-side audio player.

## Check player status [/status]
### Retrieve current status [GET]
+ Response 200 (application/json)

        { "status": "initialized" }

## Player control - load [/load]
### Load an audio file [POST]
Expects authorization key and file ID  
Returns file ID of loaded track and status:  
 ready when operation successful  
 error when an error occurred

+ Request (application/json)

        { "authKey": 93216429521, "fileID": 1 }

+ Response 201 (application/json)

        { "fileID": 1, "status": "ready" }
        
## Player control - play [/play]        
### Play currently loaded audio file [POST]
Expects authorization key
Returns status ()

+ Request (application/json)

        { "authKey": 93216429521 }

+ Response 201 (application/json)

        { "status": "playback" }

## Player control - pause [/pause]        
### Pause playback [POST]
Expects authorization key
Returns status

+ Request (application/json)

        { "authKey": 93216429521 }

+ Response 201 (application/json)

        { "status": "pause", "timeStamp": 143000 }

## Player control - stop [/stop]        
### Pause playback [POST]
Expects authorization key
Returns status

+ Request (application/json)

        { "authKey": 93216429521 }

+ Response 201 (application/json)

        { "status": "ready" }
        
## Player control - next [/next]        
### Pause playback [POST]
Expects authorization key
Returns status

+ Request (application/json)

        { "authKey": 93216429521 }

+ Response 201 (application/json)

        { "status": "playback|ready" }        
